//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Name { get; set; }
        public string BIK { get; set; }
        public string IIK { get; set; }
        public Nullable<int> Kbe { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string AccountCurrency { get; set; }
        public string Address { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
