//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.BankAccounts = new HashSet<BankAccounts>();
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public string JuridicalName { get; set; }
        public string BIN { get; set; }
        public string CompanyHeadName { get; set; }
        public Nullable<int> Oblast { get; set; }
        public Nullable<int> Region { get; set; }
        public string JuridicalAddress { get; set; }
        public string FactAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccounts> BankAccounts { get; set; }
        public virtual DicKato DicKato { get; set; }
        public virtual DicKato DicKato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
