//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DicKato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DicKato()
        {
            this.Companies = new HashSet<Companies>();
            this.Companies1 = new HashSet<Companies>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NameKz { get; set; }
        public string NameRu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Companies> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Companies> Companies1 { get; set; }
        public virtual DicKato DicKato1 { get; set; }
        public virtual DicKato DicKato2 { get; set; }
    }
}
