//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.Guid AnnouncementId { get; set; }
        public System.Guid BuyerId { get; set; }
        public System.Guid BankAccountId { get; set; }
        public string BankWarranty { get; set; }
        public string No { get; set; }
        public int Status { get; set; }
        public string XmlSign { get; set; }
    
        public virtual Announcements Announcements { get; set; }
        public virtual Users Users { get; set; }
    }
}
