//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual DicRoles DicRoles { get; set; }
        public virtual Users Users { get; set; }
    }
}
